services:
  - type: web
    name: bible-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 240
    branch: master
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ESV_API_KEY
        sync: false
      - key: API_BIBLE_KEY
        sync: false
      - key: API_BIBLE_IDS
        sync: false
