services:
  - type: web
    name: bible-generator
    env: docker
    dockerfilePath: ./Dockerfile
    branch: master
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ESV_API_KEY
        sync: false
      - key: API_BIBLE_KEY
        sync: false
      - key: API_BIBLE_IDS
        sync: false
